### ISSUE TITLE
杂话

### ISSUE THREAD

**Issue by ONLYLOVELYKISS** [Lilinzta/auto_giwifi_python#1]
话说之前不是实名了，不重新认证的不给联网，如果我用一个新注册的账号应该可以吧。

**Comment by Lilinzta** [comment]
不太明白你的意思，我账号也是实名了的，这个脚本的作用就是定时重新认证。

**Comment by ONLYLOVELYKISS** [comment]
我意思其实就是有俩账号，一个没有实名，一个自己用的，我原以为是没实名的也可以，昨天试了一下应该是得实名
<img width="758" alt="联想截图_20240710170748" src="https://github.com/Lilinzta/auto_giwifi_python/assets/88222714/2958f1ca-24e2-46a2-b966-8f492c5684d6">
